src/apps/urls.py
from django.urls import path

from . import views

app_name = "apps"
urlpatterns = [
    path("", views.apps_list_view, name="list"),
    path("create/", views.apps_create_view, name="create"),
    path("env/key/validate/", views.apps_env_validate_key, name="validate-env-key"),
    path("pk/<uuid:pk>/", views.apps_detail_backup_view, name="detail-backup"),
    path("<slug:app_id>/delete/", views.app_delete_view, name="delete"),
    path("<slug:app_id>/env/", views.apps_env_view, name="env"),
    path("<slug:app_id>/secrets/", views.apps_secrets_view, name="secrets"),
    path("<slug:app_id>/inputs/", views.apps_new_input_view, name="inputs"),
    path("<slug:app_id>/download/", views.apps_manifest_download_view, name="download"),
    path("<slug:app_id>/raw/", views.apps_rk8s_raw_view, name="raw"),
    path("<slug:app_id>/", views.apps_detail_view, name="detail"),
    # path("<uuid:pk>/env/", views.apps_env_view, name="env"),
    # path("<uuid:pk>/secrets/", views.apps_secrets_view, name="secrets"),
    # path("<uuid:pk>/inputs/", views.apps_new_input_view, name="inputs"),
    # path("<uuid:pk>/download/", views.apps_manifest_download_view, name="download"),
]

src/cfehome/urls.py
from django.conf import settings
from django.contrib import admin
from django.contrib.flatpages import views as flatpages_views
from django.urls import include, path, re_path
from django.views.generic import RedirectView, TemplateView

from articles import views as articles_views

from . import views

urlpatterns = [
    path("", views.index, name="index"),
    re_path(r"^signup/?", RedirectView.as_view(url="/account/signup/")),
    re_path(r"^sign-up/?", RedirectView.as_view(url="/account/signup/")),
    re_path(r"^join/?", RedirectView.as_view(url="/account/signup/")),
    re_path(r"^signin/?", RedirectView.as_view(url="/account/login/")),
    re_path(r"^sign-in/?", RedirectView.as_view(url="/account/login/")),
    re_path(r"^login/?", RedirectView.as_view(url="/account/login/")),
    re_path(r"^logout/?", RedirectView.as_view(url="/account/logout/")),
    re_path(r"^password-reset/?", RedirectView.as_view(url="/account/password/reset/")),
    re_path(r"^password/reset/?", RedirectView.as_view(url="/account/password/reset/")),
    path("account/", include("allauth.urls")),
    path("blog", RedirectView.as_view(url="/blog/")),
    path("blog/", include("articles.urls")),
    path("search", RedirectView.as_view(url="/search/")),
    path("search/", articles_views.SearchView.as_view(), name="search"),
    path("u/", include("profiles.urls")),
    path(
        "generator/",
        TemplateView.as_view(template_name="coming-soon.html"),
        name="generator",
    ),
    path("admin/", admin.site.urls),
    path(
        "secrets-encoder",
        TemplateView.as_view(template_name="utils/secrets-encoder.html"),
        name="secrets-encoder",
    ),
    path("webhooks/blog/", include("gh.webhooks")),
]


urlpatterns += [
    path("about/", flatpages_views.flatpage, {"url": "/about/"}, name="about"),
    path("contact/", flatpages_views.flatpage, {"url": "/contact/"}, name="contact"),
    path("sponsors/", flatpages_views.flatpage, {"url": "/sponsors/"}, name="sponsors"),
    path("privacy/", flatpages_views.flatpage, {"url": "/privacy/"}, name="privacy"),
]

if settings.DEBUG:
    from django.conf.urls.static import static

    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

urlpatterns += [
    path("healthz", views.index),
    # path("<path:resource>", TemplateView.as_view(template_name="coming-soon.html")),
]

src/console/urls.py
from django.conf import settings
from django.contrib import admin
from django.urls import include, path
from django.views.generic import RedirectView, TemplateView

from apps import views as apps_views

# from . import views

app_name = "console"

urlpatterns = [
    # path("", apps_views.apps_list_view, name="index"),
    path("", RedirectView.as_view(url="/apps/"), name="index"),
    path("apps/", include("apps.urls")),
    path("account/", include("allauth.urls")),
    path("projects/", include("projects.urls")),
]

if settings.DEBUG:
    from django.conf.urls.static import static

    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

src/projects/urls.py
from django.urls import path

from . import views

app_name = "projects"
urlpatterns = [
    path("", views.ProjectListView.as_view(), name="list"),
    path("create/", views.ProjectCreateView.as_view(), name="create"),
    path("choices/", views.projects_choices_view, name="choices"),
    path("select/", views.projects_choices_view, name="select"),
    path("<slug:project_id>/delete/", views.project_delete_view, name="delete"),
    path("<slug:project_id>/", views.ProjectDetailView.as_view(), name="detail"),
]

src/console/views.py
from django.contrib.auth.decorators import login_required
from django.shortcuts import render


@login_required(redirect_field_name=None)
def console_view(request):
    return render(request, "console/view.html", {})

src/templates/console/base.html
{% load compress %}
{% load static %}

<!DOCTYPE html>
<html lang="en">

<head>
    {% include 'base/head.html' %}
    {% block meta %}{% endblock %}
    <title>{% block head_title %}Road to Kubernetes{% endblock head_title %}</title>
</head>

<body class="bg-white dark:bg-gray-900 text-black dark:text-white" hx-headers='{"X-CSRFToken": "{{ csrf_token }}"}'>

    
    {% include 'console/navbar.html' %}


  {% include 'console/submenu.html' %}
  
    <div class="container mx-auto mt-4 min-h-screen">
        <div class="flex">
            {% include 'console/sidebar.html' %}
            <div class="flex-auto px-5">
                {% include 'base/messages.html' %}
                {% if not request.session.project_id and "/apps/" in request.path %}
                 {% include 'projects/snippets/project_required.html' %}
                {% else %}
                    {% block content %}
                    {% endblock content %}
                {% endif %}
            </div>
        </div>
    </div>

    {% include 'base/footer.html' %}
    {% include 'base/js.html' %}
     
</body>

</html>

src/templates/console/navbar.html
{% with request.path as current_page %}
{% with user.profile as user_profile %}
{% with 'block py-2 pr-4 pl-3 text-white bg-blue-700 rounded md:bg-transparent md:text-blue-700 md:p-0 dark:text-white' as active_link %}
{% with 'block py-2 pr-4 pl-3 text-gray-700 rounded hover:bg-gray-100 md:hover:bg-transparent md:hover:text-blue-700 md:p-0 md:dark:hover:text-white dark:text-gray-400 dark:hover:bg-gray-700 dark:hover:text-white md:dark:hover:bg-transparent dark:border-gray-700' as inactive_link %}


<nav class="bg-white border-gray-200 px-2 sm:px-4 py-2.5 rounded dark:bg-gray-900">
    <div class="container flex flex-wrap items-center mx-auto">
      <a href="/" class="flex items-center mr-5">
          {% include 'icons/brand.html' with extra_class='mr-1' %}
          <span class="self-center text-xl font-semibold whitespace-nowrap dark:text-white">RK8s</span>
      </a>
      <div class="flex md:order-1 md:ml-1 md:mr-auto ml-auto">
        <button type="button" data-collapse-toggle="navbar-search" aria-controls="navbar-search" aria-expanded="false" class="md:hidden  text-gray-500 dark:text-gray-400 hover:bg-gray-100 dark:hover:bg-gray-700 focus:outline-none focus:ring-4 focus:ring-gray-200 dark:focus:ring-gray-700 rounded-lg text-sm p-2.5 mr-1" >
          <svg class="w-5 h-5" aria-hidden="true" fill="currentColor" viewBox="0 0 20 20" xmlns="http://www.w3.org/2000/svg"><path fill-rule="evenodd" d="M8 4a4 4 0 100 8 4 4 0 000-8zM2 8a6 6 0 1110.89 3.476l4.817 4.817a1 1 0 01-1.414 1.414l-4.816-4.816A6 6 0 012 8z" clip-rule="evenodd"></path></svg>
          <span class="sr-only">Search</span>
        </button>
        <div class="hidden relative md:block mr-auto">
            <form method="GET" action="{{ search_url }}">
          <div class="flex absolute inset-y-0 left-0 items-center pl-3 pointer-events-none">
            <svg class="w-5 h-5 text-gray-500" aria-hidden="true" fill="currentColor" viewBox="0 0 20 20" xmlns="http://www.w3.org/2000/svg"><path fill-rule="evenodd" d="M8 4a4 4 0 100 8 4 4 0 000-8zM2 8a6 6 0 1110.89 3.476l4.817 4.817a1 1 0 01-1.414 1.414l-4.816-4.816A6 6 0 012 8z" clip-rule="evenodd"></path></svg>
            <span class="sr-only">Search icon</span>
          </div>
          <input name='q' value="{% if 'search' in current_page %}{{ request.GET.q }}{% endif %}" type="text" id="search-navbar" class="block p-2 pl-10 w-full text-gray-900 bg-gray-50 rounded-lg border border-gray-300 sm:text-sm focus:ring-blue-500 focus:border-blue-500 dark:bg-gray-700 dark:border-gray-600 dark:placeholder-gray-400 dark:text-white dark:focus:ring-blue-500 dark:focus:border-blue-500" placeholder="Search...">
        </form>
        </div>
        <button data-collapse-toggle="navbar-search" type="button" class="inline-flex items-center p-2 text-sm text-gray-500 rounded-lg md:hidden hover:bg-gray-100 focus:outline-none focus:ring-2 focus:ring-gray-200 dark:text-gray-400 dark:hover:bg-gray-700 dark:focus:ring-gray-600" aria-controls="navbar-search" aria-expanded="false">
          <span class="sr-only">Open menu</span>
          <svg class="w-6 h-6" aria-hidden="true" fill="currentColor" viewBox="0 0 20 20" xmlns="http://www.w3.org/2000/svg"><path fill-rule="evenodd" d="M3 5a1 1 0 011-1h12a1 1 0 110 2H4a1 1 0 01-1-1zM3 10a1 1 0 011-1h12a1 1 0 110 2H4a1 1 0 01-1-1zM3 15a1 1 0 011-1h12a1 1 0 110 2H4a1 1 0 01-1-1z" clip-rule="evenodd"></path></svg>
        </button>
      </div>

      <div class="flex items-center md:order-2">
        {% if user_profile and user_profile.image %}
        <button type="button" class="flex mr-3 text-sm bg-gray-800 rounded-full md:mr-0 focus:ring-4 focus:ring-gray-300 dark:focus:ring-gray-600" id="user-menu-button" aria-expanded="false" data-dropdown-toggle="user-dropdown" data-dropdown-placement="bottom">
          <span class="sr-only">Open user menu</span>
         
            <img class="w-8 h-8 rounded-full" src="{{ user_profile.image.url }}" alt="user photo">
           
        </button>

        {% else %}
        <button class="text-white bg-gray-900 dark:bg-white dark:text-gray-900 px-3 text-dark border border-blue-900 rounded-full" id="user-menu-button" aria-expanded="false" data-dropdown-toggle="user-dropdown" data-dropdown-placement="bottom">{{ user.username.0 }}</span>
      {% endif %}

        <!-- Dropdown menu -->
        <div class="hidden z-50 my-4 text-base list-none bg-white rounded divide-y divide-gray-100 shadow dark:bg-gray-700 dark:divide-gray-600" id="user-dropdown">
          <div class="py-3 px-4">
            <span class="block text-sm text-gray-900 dark:text-white">{{ user.profile.name }}</span>
            <span class="block text-sm font-medium text-gray-500 truncate dark:text-gray-400">{{ user.profile.username }}</span>
          </div>
          <ul class="py-1" aria-labelledby="user-menu-button">
            <li class="hidden">
              <a href="{{ projects_list_url }}" class="block py-2 px-4 text-sm text-gray-700 hover:bg-gray-100 dark:hover:bg-gray-600 dark:text-gray-200 dark:hover:text-white">
                  Projects
              </a>
            </li>

            <li>
              <a href="{% url 'account_logout' %}" class="block py-2 px-4 text-sm text-gray-700 hover:bg-gray-100 dark:hover:bg-gray-600 dark:text-gray-200 dark:hover:text-white">Sign out</a>
            </li>
          </ul>
        </div>
    </div>


      <div class="hidden justify-between items-center w-full md:flex md:w-auto md:order-1" id="navbar-search">
        <div class="relative mt-3 md:hidden">
          <form method="GET" action="{{ search_url }}">
          <div class="flex absolute inset-y-0 left-0 items-center pl-3 pointer-events-none">
            <svg class="w-5 h-5 text-gray-500" aria-hidden="true" fill="currentColor" viewBox="0 0 20 20" xmlns="http://www.w3.org/2000/svg"><path fill-rule="evenodd" d="M8 4a4 4 0 100 8 4 4 0 000-8zM2 8a6 6 0 1110.89 3.476l4.817 4.817a1 1 0 01-1.414 1.414l-4.816-4.816A6 6 0 012 8z" clip-rule="evenodd"></path></svg>
          </div>
          <input name='q'   value="{% if 'search' in current_page %}{{ request.GET.q }}{% endif %}" type="text" id="search-navbar" class="block p-2 pl-10 w-full text-gray-900 bg-gray-50 rounded-lg border border-gray-300 sm:text-sm focus:ring-blue-500 focus:border-blue-500 dark:bg-gray-700 dark:border-gray-600 dark:placeholder-gray-400 dark:text-white dark:focus:ring-blue-500 dark:focus:border-blue-500" placeholder="Search...">
          </form>
        </div>




        <ul class="flex flex-col p-4 mt-4 bg-gray-50 rounded-lg border border-gray-100 md:flex-row md:space-x-8 md:mt-0 md:text-sm md:font-medium md:border-0 md:bg-white dark:bg-gray-800 md:dark:bg-gray-900 dark:border-gray-700">
         
          <li>
            <a href="{{ blog_url }}" {% if "/blog/" in current_page  %}aria-current="page" {% endif %} class="{% if "/blog/" in current_page %}{{ active_link }} {% else %}  {{ inactive_link }}{% endif %}">Blog</a>
          </li>

        
        </ul>
        

      </div>

      
     
    </div>
  </nav>


  {% endwith %}
  {% endwith %}
  {% endwith %}
  {% endwith %}

src/templates/console/page-breadcrumb.html
<nav class="flex mb-4 hidden md:block " aria-label="Breadcrumb">
    <ol class="inline-flex items-center space-x-1 md:space-x-3">
     
      <li>
        <div class="flex items-center">
          <a href="{{ list_url }}" class="text-sm font-medium text-gray-700 hover:text-gray-900 dark:text-gray-400 dark:hover:text-white">{{ list_title }}</a>
        </div>
      </li>
      {% if object %}
      <li aria-current="page">
        <div class="flex items-center">
          <svg class="w-6 h-6 text-gray-400" fill="currentColor" viewBox="0 0 20 20" xmlns="http://www.w3.org/2000/svg"><path fill-rule="evenodd" d="M7.293 14.707a1 1 0 010-1.414L10.586 10 7.293 6.707a1 1 0 011.414-1.414l4 4a1 1 0 010 1.414l-4 4a1 1 0 01-1.414 0z" clip-rule="evenodd"></path></svg>
          <span class="ml-1 text-sm font-medium text-gray-500 md:ml-2 dark:text-gray-400">{{ object.display_label }}</span>
        </div>
      </li>

      {% endif %}
      
    </ol>
  </nav>

src/templates/console/page-header.html
<div class="flex mb-5 border-b-2 pb-5">
    <h2 class="text-3xl font-extrabold tracking-tight leading-none text-gray-900 md:text-4xl dark:text-white">
        {{ title }} 
    </h2>
    {% if create_url %}
    <a href="{{ create_url }}" aria-current="page" class="text-blue-700 hover:scale-105  text-center hover:text-white dark:hover:underline dark:text-white border-blue-700 bg-white hover:bg-blue-800 focus:ring-4 focus:ring-blue-300 font-medium rounded-lg border text-sm px-5 py-2.5 ml-auto dark:bg-blue-600 dark:hover:bg-blue-700 focus:outline-none dark:focus:ring-blue-800">
        Create
    </a>
    {% endif %}
</div>

src/templates/console/sidebar.html
{% url 'apps:list' as apps_list_url %}
{% url 'projects:list' as project_list_url %}
{% url 'projects:create' as project_create_url %}
{% with 'underline underline-offset-2' as active_link_class %}


<aside class="w-32 md:w-64 hidden md:block" aria-label="Sidebar">
    <div class="overflow-y-auto py-4 px-3 bg-gray-50 rounded dark:bg-gray-800">
      <div class="mb-4" hx-get="{{ projects_choices_url }}" hx-trigger="revealed">
         {% include 'projects/snippets/project_choices.html' %}
      </div>
       <ul class="space-y-2">
          <li class="hidden">
             <a href="/" class="{% if '/' == request.path %}{{ active_link_class }}{% endif %} flex items-center p-2 text-base font-normal text-gray-900 rounded-lg dark:text-white hover:bg-gray-100 dark:hover:bg-gray-700">
                
                {% include 'icons/chart.html' %}
                <span class="ml-3">Dashboard</span>
             </a>
          </li>

          <li>
            <a href="{{ apps_list_url }}" class="{% if apps_list_url in request.build_absolute_uri %}{{ active_link_class }}{% endif %} flex items-center p-2 text-base font-normal text-gray-900 rounded-lg dark:text-white hover:bg-gray-100 dark:hover:bg-gray-700">
               {% include 'icons/view-grid.html' %}
               <span class="ml-3">Apps</span>
            </a>
         </li>

         <li>
            <a href="{{ projects_list_url }}" class="{% if projects_list_url in request.build_absolute_uri %}{{ active_link_class }}{% endif %} flex items-center p-2 text-base font-normal text-gray-900 rounded-lg dark:text-white hover:bg-gray-100 dark:hover:bg-gray-700">
         
               {% include 'icons/collection.html' %}
               <span class="ml-3">Projects</span>
            </a>
         </li>

         


          <li class="hidden">
            <button type="button" class="flex items-center w-full p-2 text-base font-normal text-gray-900 transition duration-75 rounded-lg group hover:bg-gray-100 dark:text-white dark:hover:bg-gray-700" aria-controls="dropdown-example" data-collapse-toggle="dropdown-example">
                {% include 'icons/view-grid.html' %}
                  <span class="flex-1 ml-3 text-left whitespace-nowrap ">Projects</span>
                  <svg class="w-6 h-6" fill="currentColor" viewBox="0 0 20 20" xmlns="http://www.w3.org/2000/svg"><path fill-rule="evenodd" d="M5.293 7.293a1 1 0 011.414 0L10 10.586l3.293-3.293a1 1 0 111.414 1.414l-4 4a1 1 0 01-1.414 0l-4-4a1 1 0 010-1.414z" clip-rule="evenodd"></path></svg>
            </button>
            <ul id="dropdown-example" class="{% if project_list_url not in request.path %}hidden{% endif %} py-2 space-y-2">
                  <li>
                     <a href="{{ project_list_url }}" class="{% if project_list_url == request.path %}{{ active_link_class }}{% endif %} flex items-center w-full p-2 text-base font-normal text-gray-900 transition duration-75 rounded-lg pl-11 group hover:bg-gray-100 dark:text-white dark:hover:bg-gray-700">View Projects</a>
                  </li>
                  <li>
                     <a href="{{ project_create_url }}" class="{% if project_create_url == request.path %}{{ active_link_class }}{% endif %} flex items-center w-full p-2 text-base font-normal text-gray-900 transition duration-75 rounded-lg pl-11 group hover:bg-gray-100 dark:text-white dark:hover:bg-gray-700">+ Create project</a>
                  </li>
            </ul>
         </li>

          <li class="hidden">
             <a href="#" class="flex items-center p-2 text-base font-normal text-gray-900 rounded-lg dark:text-white hover:bg-gray-100 dark:hover:bg-gray-700">
                <svg aria-hidden="true" class="flex-shrink-0 w-6 h-6 text-gray-500 transition duration-75 dark:text-gray-400 group-hover:text-gray-900 dark:group-hover:text-white" fill="currentColor" viewBox="0 0 20 20" xmlns="http://www.w3.org/2000/svg"><path d="M8.707 7.293a1 1 0 00-1.414 1.414l2 2a1 1 0 001.414 0l2-2a1 1 0 00-1.414-1.414L11 7.586V3a1 1 0 10-2 0v4.586l-.293-.293z"></path><path d="M3 5a2 2 0 012-2h1a1 1 0 010 2H5v7h2l1 2h4l1-2h2V5h-1a1 1 0 110-2h1a2 2 0 012 2v10a2 2 0 01-2 2H5a2 2 0 01-2-2V5z"></path></svg>
                <span class="flex-1 ml-3 whitespace-nowrap">Inbox</span>
                <span class="inline-flex justify-center items-center p-3 ml-3 w-3 h-3 text-sm font-medium text-blue-600 bg-blue-200 rounded-full dark:bg-blue-900 dark:text-blue-200">3</span>
             </a>
          </li>
          <li  class="hidden">
             <a href="#" class="flex items-center p-2 text-base font-normal text-gray-900 rounded-lg dark:text-white hover:bg-gray-100 dark:hover:bg-gray-700">
                <svg aria-hidden="true" class="flex-shrink-0 w-6 h-6 text-gray-500 transition duration-75 dark:text-gray-400 group-hover:text-gray-900 dark:group-hover:text-white" fill="currentColor" viewBox="0 0 20 20" xmlns="http://www.w3.org/2000/svg"><path fill-rule="evenodd" d="M10 9a3 3 0 100-6 3 3 0 000 6zm-7 9a7 7 0 1114 0H3z" clip-rule="evenodd"></path></svg>
                <span class="flex-1 ml-3 whitespace-nowrap">Users</span>
             </a>
          </li>
          <li  class="hidden">
             <a href="#" class="flex items-center p-2 text-base font-normal text-gray-900 rounded-lg dark:text-white hover:bg-gray-100 dark:hover:bg-gray-700">
                <svg aria-hidden="true" class="flex-shrink-0 w-6 h-6 text-gray-500 transition duration-75 dark:text-gray-400 group-hover:text-gray-900 dark:group-hover:text-white" fill="currentColor" viewBox="0 0 20 20" xmlns="http://www.w3.org/2000/svg"><path fill-rule="evenodd" d="M10 2a4 4 0 00-4 4v1H5a1 1 0 00-.994.89l-1 9A1 1 0 004 18h12a1 1 0 00.994-1.11l-1-9A1 1 0 0015 7h-1V6a4 4 0 00-4-4zm2 5V6a2 2 0 10-4 0v1h4zm-6 3a1 1 0 112 0 1 1 0 01-2 0zm7-1a1 1 0 100 2 1 1 0 000-2z" clip-rule="evenodd"></path></svg>
                <span class="flex-1 ml-3 whitespace-nowrap">Products</span>
             </a>
          </li>
          <li  class="hidden">
             <a href="#" class="flex items-center p-2 text-base font-normal text-gray-900 rounded-lg dark:text-white hover:bg-gray-100 dark:hover:bg-gray-700">
                <svg aria-hidden="true" class="flex-shrink-0 w-6 h-6 text-gray-500 transition duration-75 dark:text-gray-400 group-hover:text-gray-900 dark:group-hover:text-white" fill="currentColor" viewBox="0 0 20 20" xmlns="http://www.w3.org/2000/svg"><path fill-rule="evenodd" d="M3 3a1 1 0 00-1 1v12a1 1 0 102 0V4a1 1 0 00-1-1zm10.293 9.293a1 1 0 001.414 1.414l3-3a1 1 0 000-1.414l-3-3a1 1 0 10-1.414 1.414L14.586 9H7a1 1 0 100 2h7.586l-1.293 1.293z" clip-rule="evenodd"></path></svg>
                <span class="flex-1 ml-3 whitespace-nowrap">Sign In</span>
             </a>
          </li>
          <li  class="hidden">
             <a href="#" class="flex items-center p-2 text-base font-normal text-gray-900 rounded-lg dark:text-white hover:bg-gray-100 dark:hover:bg-gray-700">
                <svg aria-hidden="true" class="flex-shrink-0 w-6 h-6 text-gray-500 transition duration-75 dark:text-gray-400 group-hover:text-gray-900 dark:group-hover:text-white" fill="currentColor" viewBox="0 0 20 20" xmlns="http://www.w3.org/2000/svg"><path fill-rule="evenodd" d="M5 4a3 3 0 00-3 3v6a3 3 0 003 3h10a3 3 0 003-3V7a3 3 0 00-3-3H5zm-1 9v-1h5v2H5a1 1 0 01-1-1zm7 1h4a1 1 0 001-1v-1h-5v2zm0-4h5V8h-5v2zM9 8H4v2h5V8z" clip-rule="evenodd"></path></svg>
                <span class="flex-1 ml-3 whitespace-nowrap">Sign Up</span>
             </a>
          </li>
       </ul>
    </div>
 </aside>
 {% endwith %}

src/templates/console/submenu.html
{% url 'apps:list' as apps_list_url %}
{% url 'projects:list' as project_list_url %}
{% url 'projects:create' as project_create_url %}
{% with 'underline underline-offset-2' as active_link_class %}
<nav class="bg-gray-50 dark:bg-gray-700 block md:hidden">
    <div class="py-3 px-4 mx-auto max-w-screen-xl md:px-6">
        <div class="flex items-center">
            <ul class="flex flex-row mt-0 mr-6 space-x-8 text-sm font-medium">
                <li>
                    <a href="{{ apps_list_url }}" class="text-gray-900 dark:text-white hover:underline">Apps</a>
                </li>
                <li>
                    <a href="{{ project_list_url }}" class="text-gray-900 dark:text-white hover:underline">Projects</a>
                </li>

               
            </ul>
            {% if request.session.project_id %}
                <button hx-get="{{ projects_choices_url }}" hx-trigger="click" hx-target="#submenu-project-dropdown" data-dropdown-toggle="submenu-project-dropdown" class="text-gray-600 text-sm dark:text-gray-300 ml-auto">{{ request.session.project_id }}</button>

              

                <div id="submenu-project-dropdown" class="hidden  border mr-4 z-10 w-5/6 p-3 bg-gray-50 dark:bg-gray-700 rounded divide-y divide-gray-100 shadow">
                    {% include 'projects/snippets/project_choices.html' %}
                </div>
            {% endif %}
            
        </div>
        
    </div>
</nav>
{% endwith %}

src/templates/console/view.html
{% extends "console/base.html" %}

{% block content %}

{{ user }}

{{ request.session.project_id }}

{% endblock content %}